import type { Product } from './types';

// Catálogo de demostración: se muestra mientras la tienda todavía no tiene
// productos propios cargados desde el panel (o mientras Firebase no está
// configurado), para que la página se vea completa desde el primer día. En
// cuanto se publica el primer producto real desde /admin, este catálogo deja
// de mostrarse automáticamente.

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&h=1200&q=80`;

const ADULT_SIZES = ['36', '37', '38', '39', '40', '41', '42', '43'];
const MEN_SIZES = ['38', '39', '40', '41', '42', '43', '44'];
const WOMEN_SIZES = ['35', '36', '37', '38', '39', '40'];

const DAY = 24 * 60 * 60 * 1000;
const BASE = Date.UTC(2026, 8, 1);

const REVIEWS = {
  sneaker: [
    { name: 'Andrés M.', city: 'Quito', rating: 5, text: 'Llegaron con su caja en 2 días, full recomendados.' },
    { name: 'Carla R.', city: 'Guayaquil', rating: 5, text: 'La talla exacta con la guía. Súper cómodos, de una vuelvo a comprar.' },
    { name: 'Jorge P.', city: 'Ambato', rating: 4, text: 'Chévere el modelo. Pagué contra entrega y todo salió bien.' },
  ],
  running: [
    { name: 'Diego S.', city: 'Cuenca', rating: 5, text: 'Los uso para correr en la mañana, la amortiguación es otra cosa. Bacán.' },
    { name: 'Paola L.', city: 'Loja', rating: 5, text: 'Muy livianos. Me asesoraron por WhatsApp con la talla y quedaron perfectos.' },
  ],
};

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-on-cloudtec',
    slug: 'on-cloud-cloudtec-phase',
    title: 'On Cloud · CloudTec Phase®',
    brand: 'On',
    gender: 'unisex',
    description:
      'Ingeniería suiza para correr y caminar como sobre nubes. La suela CloudTec Phase® se comprime como un dominó en cada pisada para darte una transición suavecita y un impulso natural hacia adelante.\n\n• Amortiguación CloudTec Phase®\n• Capellada tejida ultraligera y transpirable\n• Diseño Swiss Engineering\n• Perfectos para correr, entrenar o el día a día\n• Incluye su caja',
    price: 189.99,
    compareAtPrice: 219.99,
    images: ['/products/on-cloudtec-phase.jpg', '/products/on-cloudtec-phase-cutout.png'],
    sizes: ADULT_SIZES,
    colors: [{ name: 'Pearl / Fog', hex: '#C9C3BA' }],
    collection: 'running',
    fit: 'normal',
    stock: 6,
    featured: true,
    isNew: true,
    active: true,
    soldCount: 634,
    reviewsCount: 187,
    reviews: [
      { name: 'Sebastián R.', city: 'Quito', rating: 5, text: 'Lo más cómodo que he usado en mi vida, literal se siente como caminar en nubes. Y llegaron al día siguiente.' },
      { name: 'Camila E.', city: 'Guayaquil', rating: 5, text: 'Full bonitos en persona, el color es elegantísimo. Los uso para el gym y para salir. De una los recomiendo.' },
      { name: 'Mateo V.', city: 'Cuenca', rating: 5, text: 'Pagué contra entrega, adelanté los $5 y todo perfecto. La talla exacta con la calculadora.' },
    ],
    createdAt: BASE,
  },
  {
    id: 'demo-af1',
    slug: 'nike-air-force-1-07-blanco',
    title: "Nike Air Force 1 '07",
    brand: 'Nike',
    gender: 'unisex',
    description:
      'El clásico que nunca pasa de moda. Cuero premium, suela Air para amortiguación todo el día y ese blanco total que combina con todo.\n\n• Capellada de cuero\n• Unidad Air encapsulada en el talón\n• Suela de goma con patrón de pivote\n• Incluye su caja',
    price: 119.99,
    compareAtPrice: 149.99,
    images: [img('photo-1600269452121-4f2416e55c28'), img('photo-1549298916-b41d501d3772')],
    sizes: ADULT_SIZES,
    colors: [{ name: 'Blanco', hex: '#FFFFFF' }],
    collection: 'urbanos',
    fit: 'grande',
    stock: 7,
    featured: true,
    isNew: false,
    active: true,
    soldCount: 412,
    reviewsCount: 128,
    reviews: REVIEWS.sneaker,
    createdAt: BASE - 40 * DAY,
  },
  {
    id: 'demo-samba',
    slug: 'adidas-samba-og',
    title: 'Adidas Samba OG',
    brand: 'Adidas',
    gender: 'unisex',
    description:
      'El ícono de la cancha que se tomó la calle. Capellada de cuero suave, puntera de gamuza y la clásica suela de goma color caramelo.\n\n• Cuero y gamuza\n• Suela de goma natural\n• Horma baja clásica\n• Incluye su caja',
    price: 109.99,
    compareAtPrice: 129.99,
    images: [img('photo-1608231387042-66d1773070a5'), img('photo-1525966222134-fcfa99b8ae77')],
    sizes: ADULT_SIZES,
    colors: [
      { name: 'Blanco / Negro', hex: '#F5F5F5' },
      { name: 'Negro', hex: '#111111' },
    ],
    collection: 'urbanos',
    fit: 'pequena',
    stock: 5,
    featured: true,
    isNew: true,
    active: true,
    soldCount: 356,
    reviewsCount: 97,
    reviews: REVIEWS.sneaker,
    createdAt: BASE - 2 * DAY,
  },
  {
    id: 'demo-nb530',
    slug: 'new-balance-530',
    title: 'New Balance 530',
    brand: 'New Balance',
    gender: 'unisex',
    description:
      'Estética running de los 2000 con comodidad de hoy. Malla transpirable, detalles metalizados y amortiguación ABZORB.\n\n• Malla y cuero sintético\n• Mediasuela ABZORB\n• Suela de goma de alta tracción',
    price: 99.99,
    compareAtPrice: 124.99,
    images: [img('photo-1539185441755-769473a23570'), img('photo-1560769629-975ec94e6a86')],
    sizes: ADULT_SIZES,
    colors: [
      { name: 'Blanco / Plata', hex: '#E9E9E9' },
      { name: 'Gris', hex: '#9CA3AF' },
    ],
    collection: 'running',
    fit: 'normal',
    stock: 12,
    featured: true,
    isNew: true,
    active: true,
    soldCount: 289,
    reviewsCount: 74,
    reviews: REVIEWS.running,
    createdAt: BASE - 1 * DAY,
  },
  {
    id: 'demo-airmax90',
    slug: 'nike-air-max-90',
    title: 'Nike Air Max 90',
    brand: 'Nike',
    gender: 'hombre',
    description:
      'La unidad Air visible que cambió la historia. Diseño agresivo, amortiguación brutal y el estilo de las calles de los 90.\n\n• Unidad Max Air visible\n• Capellada de cuero y textil\n• Suela waffle de goma',
    price: 129.99,
    compareAtPrice: 159.99,
    images: [img('photo-1595950653106-6c9ebd614d3a'), img('photo-1606107557195-0e29a4b5b4aa')],
    sizes: MEN_SIZES,
    colors: [{ name: 'Multicolor', hex: '#E4572E' }],
    collection: 'deportivos',
    fit: 'normal',
    stock: 4,
    featured: true,
    active: true,
    soldCount: 198,
    reviewsCount: 61,
    reviews: REVIEWS.sneaker,
    createdAt: BASE - 15 * DAY,
  },
  {
    id: 'demo-pegasus',
    slug: 'nike-pegasus-41-running',
    title: 'Nike Pegasus 41',
    brand: 'Nike',
    gender: 'hombre',
    description:
      'Tu compañero para cada kilómetro. Espuma ReactX más suave y con más retorno de energía, ideal para entrenar todos los días.\n\n• Espuma ReactX\n• Unidades Air Zoom en antepié y talón\n• Malla técnica transpirable',
    price: 139.99,
    compareAtPrice: null,
    images: [img('photo-1542291026-7eec264c27ff'), img('photo-1491553895911-0055eca6402d')],
    sizes: MEN_SIZES,
    colors: [{ name: 'Rojo', hex: '#DC2626' }],
    collection: 'running',
    fit: 'normal',
    stock: 9,
    featured: true,
    isNew: true,
    active: true,
    soldCount: 143,
    reviewsCount: 38,
    reviews: REVIEWS.running,
    createdAt: BASE - 3 * DAY,
  },
  {
    id: 'demo-jordan1',
    slug: 'air-jordan-1-mid',
    title: 'Air Jordan 1 Mid',
    brand: 'Jordan',
    gender: 'unisex',
    description:
      'La leyenda de la cancha que manda en la calle. Silueta de caña media, cuero de calidad y el Wings logo que todos reconocen.\n\n• Capellada de cuero\n• Unidad Air en el talón\n• Suela de goma con patrón de pivote\n• Incluye su caja',
    price: 149.99,
    compareAtPrice: 174.99,
    images: [img('photo-1514989940723-e8e51635b782'), img('photo-1463100099107-aa0980c362e6')],
    sizes: ADULT_SIZES,
    colors: [{ name: 'Negro / Blanco', hex: '#111111' }],
    collection: 'urbanos',
    fit: 'normal',
    stock: 8,
    featured: true,
    active: true,
    soldCount: 318,
    reviewsCount: 96,
    reviews: REVIEWS.sneaker,
    createdAt: BASE - 60 * DAY,
  },
  {
    id: 'demo-oldskool',
    slug: 'vans-old-skool',
    title: 'Vans Old Skool',
    brand: 'Vans',
    gender: 'unisex',
    description:
      'La línea lateral más reconocida del skate. Gamuza y lona resistentes, cuello acolchado y la suela waffle de siempre.\n\n• Gamuza y lona\n• Cuello acolchado\n• Suela waffle de goma',
    price: 74.99,
    compareAtPrice: 89.99,
    images: [img('photo-1525966222134-fcfa99b8ae77'), img('photo-1543508282-6319a3e2621f')],
    sizes: ADULT_SIZES,
    colors: [{ name: 'Negro / Blanco', hex: '#111111' }],
    collection: 'urbanos',
    fit: 'normal',
    stock: 14,
    featured: false,
    active: true,
    soldCount: 267,
    reviewsCount: 82,
    reviews: REVIEWS.sneaker,
    createdAt: BASE - 25 * DAY,
  },
  {
    id: 'demo-suede',
    slug: 'puma-suede-classic',
    title: 'Puma Suede Classic XXI',
    brand: 'Puma',
    gender: 'unisex',
    description:
      'Desde 1968 marcando estilo. Gamuza suave, la Formstrip lateral y una suela de goma cómoda para todo el día.\n\n• Capellada de gamuza\n• Plantilla SoftFoam+\n• Suela de goma',
    price: 79.99,
    compareAtPrice: 99.99,
    images: [img('photo-1608231387042-66d1773070a5'), img('photo-1600185365483-26d7a4cc7519')],
    sizes: ADULT_SIZES,
    colors: [{ name: 'Azul marino', hex: '#1E3A8A' }],
    collection: 'urbanos',
    fit: 'normal',
    stock: 6,
    featured: false,
    active: true,
    soldCount: 131,
    reviewsCount: 29,
    reviews: REVIEWS.sneaker,
    createdAt: BASE - 20 * DAY,
  },
  {
    id: 'demo-ultraboost',
    slug: 'adidas-ultraboost-light',
    title: 'Adidas Ultraboost Light',
    brand: 'Adidas',
    gender: 'mujer',
    description:
      'La Ultraboost más liviana de la historia. Espuma Light BOOST con retorno de energía increíble y tejido Primeknit que se adapta a tu pie.\n\n• Mediasuela Light BOOST\n• Capellada Primeknit+\n• Suela Continental™',
    price: 149.99,
    compareAtPrice: 189.99,
    images: [img('photo-1587563871167-1ee9c731aefb'), img('photo-1606107557195-0e29a4b5b4aa')],
    sizes: WOMEN_SIZES,
    colors: [{ name: 'Blanco / Rosado', hex: '#F9D5E5' }],
    collection: 'running',
    fit: 'pequena',
    stock: 3,
    featured: true,
    active: true,
    soldCount: 176,
    reviewsCount: 44,
    reviews: REVIEWS.running,
    createdAt: BASE - 10 * DAY,
  },
  {
    id: 'demo-clubc',
    slug: 'reebok-club-c-85',
    title: 'Reebok Club C 85 Vintage',
    brand: 'Reebok',
    gender: 'mujer',
    description:
      'Estilo tenis retro con cuero suave y un toque vintage. Cómodos, livianos y perfectos para el día a día.\n\n• Cuero suave\n• Forro de felpa\n• Suela de goma',
    price: 84.99,
    compareAtPrice: 99.99,
    images: [img('photo-1600185365483-26d7a4cc7519'), img('photo-1549298916-b41d501d3772')],
    sizes: WOMEN_SIZES,
    colors: [{ name: 'Tiza / Verde', hex: '#EDE9DD' }],
    collection: 'urbanos',
    fit: 'normal',
    stock: 8,
    featured: false,
    isNew: true,
    active: true,
    soldCount: 88,
    reviewsCount: 21,
    reviews: REVIEWS.sneaker,
    createdAt: BASE - 4 * DAY,
  },
  {
    id: 'demo-gel',
    slug: 'asics-gel-1130',
    title: 'ASICS GEL-1130',
    brand: 'Asics',
    gender: 'unisex',
    description:
      'Look running de los 2000 con tecnología GEL en el talón. Tendencia total y comodidad de verdad.\n\n• Amortiguación GEL\n• Malla y cuero sintético\n• Suela de goma AHAR',
    price: 114.99,
    compareAtPrice: 134.99,
    images: [img('photo-1560769629-975ec94e6a86'), img('photo-1539185441755-769473a23570')],
    sizes: ADULT_SIZES,
    colors: [{ name: 'Blanco / Plata', hex: '#E5E7EB' }],
    collection: 'running',
    fit: 'normal',
    stock: 10,
    featured: false,
    active: true,
    soldCount: 102,
    reviewsCount: 27,
    reviews: REVIEWS.running,
    createdAt: BASE - 8 * DAY,
  },
  {
    id: 'demo-ua-hovr',
    slug: 'under-armour-hovr-phantom',
    title: 'Under Armour HOVR Phantom',
    brand: 'Under Armour',
    gender: 'hombre',
    description:
      'Amortiguación HOVR™ que devuelve energía en cada paso, con un ajuste tipo calcetín que abraza el pie. Para entrenar y para el día a día.\n\n• Amortiguación HOVR™\n• Capellada tejida con ajuste de compresión\n• Suela de goma de alta tracción',
    price: 129.99,
    compareAtPrice: 154.99,
    images: [img('photo-1606107557195-0e29a4b5b4aa'), img('photo-1539185441755-769473a23570')],
    sizes: MEN_SIZES,
    colors: [{ name: 'Negro', hex: '#111111' }],
    collection: 'deportivos',
    fit: 'normal',
    stock: 9,
    featured: false,
    active: true,
    soldCount: 94,
    reviewsCount: 23,
    reviews: REVIEWS.running,
    createdAt: BASE - 12 * DAY,
  },
  {
    id: 'demo-hoka-clifton',
    slug: 'hoka-clifton-9',
    title: 'HOKA Clifton 9',
    brand: 'Hoka',
    gender: 'unisex',
    description:
      'Máxima amortiguación con peso pluma. La favorita para correr largas distancias o pasar todo el día de pie sin cansarte.\n\n• Mediasuela de espuma de alta resiliencia\n• Geometría Meta-Rocker para una pisada fluida\n• Capellada de malla transpirable',
    price: 159.99,
    compareAtPrice: 179.99,
    images: [img('photo-1600185365483-26d7a4cc7519'), img('photo-1560769629-975ec94e6a86')],
    sizes: ADULT_SIZES,
    colors: [{ name: 'Blanco / Negro', hex: '#F3F4F6' }],
    collection: 'running',
    fit: 'normal',
    stock: 7,
    featured: true,
    isNew: true,
    active: true,
    soldCount: 211,
    reviewsCount: 58,
    reviews: REVIEWS.running,
    createdAt: BASE - 5 * DAY,
  },
  {
    id: 'demo-onitsuka-66',
    slug: 'onitsuka-tiger-mexico-66',
    title: 'Onitsuka Tiger Mexico 66',
    brand: 'Onitsuka Tiger',
    gender: 'unisex',
    description:
      'Un ícono japonés desde 1966. Perfil delgado, las franjas Tiger y un estilo retro que combina con todo.\n\n• Capellada de cuero y gamuza\n• Refuerzo cruzado en el talón\n• Suela de goma delgada y flexible',
    price: 139.99,
    compareAtPrice: 159.99,
    images: [img('photo-1549298916-b41d501d3772'), img('photo-1525966222134-fcfa99b8ae77')],
    sizes: ADULT_SIZES,
    colors: [{ name: 'Amarillo / Negro', hex: '#F2C230' }],
    collection: 'urbanos',
    fit: 'pequena',
    stock: 5,
    featured: true,
    isNew: true,
    active: true,
    soldCount: 176,
    reviewsCount: 41,
    reviews: REVIEWS.sneaker,
    createdAt: BASE - 6 * DAY,
  },
];
